data/ecosystems/t/tezos.toml
Add the iOS version and update the Android URL of Cortez
=>  Update Cortez Wallet URLs

data/ecosystems/l/liquality.toml
Atomic Swap between BTC, DAI, and ETH with minimal risk and fees, while maintaining control over your private keys
=> Adding Liquality

data/ecosystems/b/bitmark.toml
Hi,
I am from https://bitmark.com
We are making Bitmark blockchain - a property system for the digital generation.
I have added toml file, please help to review.
Best,
Cuong
=> Adding Bitmark blockchain

data/ecosystems/s/smilo.toml
Hi,
I would like to request adding Smilo as a protocol to the list.
Thank you.
=> Add smilo.toml for the Smilo Protocol - www.smilo.foundation

data/ecosystems/t/tezos.toml
Add Baking Bad organization into the Tezos ecosystem and remove obsolete repository
=> Add Baking Bad organization

data/ecosystems/t/tezos.toml
Add Teztracker repos into the Tezos ecosystem
=> Add Teztracker repos

data/ecosystems/d/daml.toml
Adding DAML.
For PR reviewers: [DAML](daml.com) is an open source smart contract language and tech stack with a runtime that leverages a wide variety of blockchains/distributed ledgers for persistence and consensus.
Note: I work for Digital Asset who are the creators and primary maintainers of this language.
=> ADD: DAML programming language

data/ecosystems/e/edgeware.toml
Learn more at https://commonwealth.im/edgeware/discussions/wg-builders
=> Edgeware has Edgeware Builders Guild

data/ecosystems/p/polkadot.toml, data/ecosystems/s/stafi.toml
Add more repositories for Stafi.
Many thanks.
=> Add Stafi related repositories

data/ecosystems/s/solana.toml
Hey Electric Capital team,
I added a few repositories of note here. Thanks for keeping this updated!
Ryan
=> Solana projects

data/ecosystems/e/ethereum.toml, data/ecosystems/s/saddle.toml
Website: https://saddle.finance/
Twitter: https://twitter.com/saddlefinance
🤠
=> Add Saddle

data/ecosystems/c/celo.toml
=> Add celo-org/gitcoin repo

data/ecosystems/s/skynet.toml
[Nebulous Labs](https://github.com/NebulousLabs) will be splitting into two organizations, one being [Skynet Labs](https://github.com/SkynetLabs). This PR adds Skynet Labs and its associated git repositories.
=> Add Skynet Labs repos

data/ecosystems/c/celo.toml
Update celo.toml for Project SmartLoan.
=> Update celo.toml for Project SmartLoan

data/ecosystems/l/lightning.toml
=> updated lightning.toml

data/ecosystems/e/elrond.toml
New repo for ElrondNetwork Blockchain
https://github.com/elrondex/elrondex
=> Add Elrondex - Elixir library to interact with Elrond Blockchain

data/ecosystems/b/blockcore.toml
- Adds Blockcore to the ecosystems list. Including the most relevant organizations and repositories.
=> Add Blockcore to ecosystems

data/ecosystems/c/cosmos.toml
Informal Systems is a core developer in the Cosmos ecosystem. https://informal.systems/
=> add informal systems, iqlusion, strange love ventures contributions to cosmos

data/ecosystems/f/flow.toml
Adding more repos, especially those that integrate with FCL.js, the Flow Client Library (i.e. any app building on Flow)
=> Adding more repos

data/ecosystems/x/xrp.toml
=> update xrp.toml - add github org XRPLF

data/ecosystems/c/cardano.toml
Addition of HeliosLang repository
=> Addition of HeliosLang DSL for Cardano

data/ecosystems/a/aktionariat.toml
Ecosystem for security tokens in Switzerland
=> Added Aktionariat ecosystem

data/ecosystems/i/internet-computer.toml
Updated internet computer with latest ecosystem repos.
=> Updated internet computer with latest ecosystem repos.

data/ecosystems/n/near.toml
here is the new link as Andrew who manages this repo is now gone gone.
=> Update Aurora subecosystem link

data/ecosystems/a/arcadia-finance.toml, data/ecosystems/e/ethereum.toml
Created `arcadia-finance.toml` & updated `ethereum.toml`'s sub_ecosystems.
=> Add Arcadia Finance

data/ecosystems/a/ashswap.toml, data/ecosystems/c/cantina.toml, data/ecosystems/e/elrond.toml, data/ecosystems/i/itheum.toml
Updated the repo list for Elrond.
=> added new repos from Elrond Community

data/ecosystems/a/anagolay.toml, data/ecosystems/p/polkadot.toml
=> Add Anagolay to taxonomy

data/ecosystems/t/ton.toml
Project page: https://ton.org
Added all GitHub organizations of TON and repositories from them.
=> Added TON ecosystem with ton.toml file

data/ecosystems/s/stacks.toml
Collected an updated list of Github repositories related to Stacks development
=> Update the stacks.toml with new 2022 repositories

data/ecosystems/i/internet-computer.toml
Internet computer (dfinity) repos updated with latest data
=> Updated Internet computer repos

data/ecosystems/o/omnidex.toml, data/ecosystems/s/symbiosis-finance.toml, data/ecosystems/t/telos.toml, data/ecosystems/z/zappy.toml
Added Telos Network active repos under telos.toml. 
Next step is to create .tomls for the sub ecosystems then add under telos sub ecosystem.
=> Telos Network Active repos

data/ecosystems/d/dovu.toml
Updates to dovu.toml to reflect its building in the Hedera ecosystem
=> Updates to dovu.toml

data/ecosystems/b/bitquery.toml, data/ecosystems/c/collab-land.toml, data/ecosystems/m/moonbeam.toml, data/ecosystems/m/moonsama.toml, data/ecosystems/o/omnisea.toml, data/ecosystems/p/polkadot-name-system.toml, data/ecosystems/s/showme.toml, data/ecosystems/z/zoodao.toml, data/ecosystems/z/zoombies.toml
add and update various projects
=> add and update various projects

data/ecosystems/a/algorand.toml, data/ecosystems/o/opulous.toml
=> Add Opulous to taxonomy

data/ecosystems/d/db3.toml
Hi, I am the co-founder of the dbpunk labs and hope to join the lists. our product is the db3 network, a community-driven decentralized layer2 database network.
=> Add db3 network to the crypto-ecosystems

data/ecosystems/a/arbitrum.toml, data/ecosystems/a/avalanche.toml, data/ecosystems/e/ethereum.toml, data/ecosystems/p/polygon.toml, data/ecosystems/s/suberra.toml
Added Suberra's URL to Github to the ecosystem data.
https://suberra.com
=> Added Suberra's data

data/ecosystems/t/tezos.toml
Added tez.capital, makers of BakeBuddy, GovBuddy & PayBuddy
=> tez.capital & groktech Tezos orgs/repos

data/ecosystems/t/tezos.toml
Added: Kanvas
Removed: Prediction markets & systemMD
=> Edited TZconnect repos

data/ecosystems/a/avalanche.toml, data/ecosystems/h/hedgefarm.toml
Adding HedgeFarm as a sub-ecosystem of Avalanche.
=> Update avalanche.toml to add HedgeFarm

data/ecosystems/a/ammer-tech.toml, data/ecosystems/a/astral.toml, data/ecosystems/b/byterocket.toml, data/ecosystems/c/celo.toml, data/ecosystems/c/celostrials.toml, data/ecosystems/e/ethic-hub.toml, data/ecosystems/f/fiat-connect.toml, data/ecosystems/g/grassroots-economics.toml, data/ecosystems/i/immortal.toml, data/ecosystems/i/into-the-verse.toml, data/ecosystems/k/kolektivo.toml, data/ecosystems/m/mento-protocol.toml, data/ecosystems/m/mintdropz.toml, data/ecosystems/m/moss-earth.toml, data/ecosystems/n/node-fi.toml, data/ecosystems/n/numoen.toml, data/ecosystems/o/open-earth.toml, data/ecosystems/p/pinnata.toml, data/ecosystems/s/spirals-protocol.toml, data/ecosystems/t/tatum.toml, data/ecosystems/v/valora.toml
Celo aligned projects:
Spiral - https://github.com/spiralsprotocol
EthicHub - https://github.com/EthicHub
GoodDollar - https://github.com/GoodDollar
Numoen - https://github.com/Numoen
ImmortalDAO - https://github.com/ImmortalDAO-fi
Celostrial - [https://github.com/Celostrials](https://github.com/Celostrials/celostrials-dapp)
Ammer Wallet - https://github.com/Ammer-Tech
Mintdropz - https://github.com/mintdrop-xyz
Kresko (started on Celo) - https://github.com/kreskohq/
Toucan: https://github.com/ToucanProtocol
Kolektivo: https://github.com/orgs/Kolektivo
Astral: https://github.com/astralprotocol
OpenEarth: https://github.com/Open-Earth-Foundation
Curve Labs: https://github.com/Curve-Labs (not curve.fi)
Byte Rocket: https://github.com/byterocket 
Moss Earth - https://github.com/moss-earth …
=> Update Celo.toml and corresponding sub-ecosystems

data/ecosystems/c/chia.toml
Cryptographic utilities in Dart for the Chia blockchain with a functional object model for manipulating Chia primitive types.
=> Add Chia Crypto Utils

data/ecosystems/m/multiversx-elrond.toml
=> Multiversx january (Part1)

data/ecosystems/m/multiversx-elrond.toml
We migrated all our repos to the new organization `https://github.com/multiversx`
=> rename organization to multiversx

data/ecosystems/c/chia.toml
- add [yyolk/dexie.py](https://github.com/yyolk/dexie.py)
- includes relevant tags, `Python`, `Client`, `Dexie` for the entry
- removes extraneous newline
=> update chia.toml add yyolk/dexie.py

data/ecosystems/c/celo.toml
Trying to help Redstone Team associate their project with Celo ecosystem. Please see (#417).
=> Add correct Redstone Finance subecosystem

data/ecosystems/b/bitcoin.toml
all of my relevant bitcoin projects
=> add Jameson Lopp's Bitcoin repositories

data/ecosystems/a/akash-network.toml
We recently migrated Akash related source code to a dedicated [organization](https://github.com/akash-network).
=> Update Akash Network

data/ecosystems/c/cosmos.toml
BOOT is a CosmWasm smart-contract scripting library. Ans-scraper scrapes assets, pools, channels, and contracts for Cosmos chains.
=> Add Abstract-OS developer tools to Cosmos ecosystem

data/ecosystems/x/xrp.toml, data/ecosystems/x/xrpl-labs-xumm.toml
- Removed some irrelevant repos
- Added some new Xumm/XRPL Labs repos manually
- Fix xum » Xumm reference
- Community repos using: https://gist.github.com/WietseWind/84247057280279a0a2e80ff2771e2fc8
- Update XRPL Labs / WietseWind contributions to XRPL ecosystem
=> Add XRPL community/dev contributions

data/ecosystems/a/algopoap.toml, data/ecosystems/a/algorand.toml
Adding AlgoPoaP: Proof of Attendance (Soon Proof of Anything) Protocol on Algorand.
=> Adding AlgoPoaP

data/ecosystems/t/thorchain.toml
Added additional repos / sub-reops that are being worked on.
=> Added repos for THORChain

data/ecosystems/m/multiversx-elrond.toml, data/ecosystems/p/peermehq.toml
Hello,
this is the first update for January in the MultiversX Ecosystem.
=> first update for january

data/ecosystems/a/adax.toml, data/ecosystems/a/axo.toml, data/ecosystems/c/cardano.toml, data/ecosystems/g/genius-tield.toml, data/ecosystems/m/meld.toml, data/ecosystems/m/muesli-swap.toml, data/ecosystems/t/teddy-swap.toml, data/ecosystems/w/wingriders.toml
minor updates for cardano ecosystems
=> cardano updates 1

data/ecosystems/r/rsk-smart-bitcoin.toml
=> Removing RskSwap as subecosystem for Rootstock

data/ecosystems/t/ton.toml
Add missed organizations and repositories for The Open Network (TON)
=> Update TON repositories

data/ecosystems/f/flow.toml
Added new Flow repos and removed a couple incorrect ones as I QA'd the list
=> Additional Flow repos

data/ecosystems/a/algopoap.toml, data/ecosystems/a/algorand.toml
Rebranded AlgoPoaP ---> AlgoPOAP and updated associated algorand.toml and algopoap.toml
=> Updating AlgoPOAP

data/ecosystems/c/canto.toml
- adding repo for canto.io web app
=> Add Canto.io Repo

data/ecosystems/o/openproduct.toml, data/ecosystems/t/ton.toml
Update the list of repositories in TON ecosystem
=> Add new repositories to TON ecosystem

data/ecosystems/o/optimism.toml
=> Add OP Stack Clients to Optimism

data/ecosystems/a/arbitrum.toml, data/ecosystems/a/aurora.toml, data/ecosystems/a/avalanche.toml, data/ecosystems/b/bitgert.toml, data/ecosystems/b/bnb-chain.toml, data/ecosystems/e/ethereum.toml, data/ecosystems/f/fantom.toml, data/ecosystems/k/kenshi.toml, data/ecosystems/p/polygon.toml
Adds https://kenshi.io:
- Create `kenshi.toml` in `data/ecosystems/k`
- Add Kenshi to `arbitrum.toml`, `aurora.toml`, `avalanche.toml`, `bitgert.toml`, `bnb-chain.toml`, `ethereum.toml`, `fantom.toml`, and `polygon.toml`
=> Add Kenshi to taxonomy

data/ecosystems/x/xrp.toml
=> add more of my public

data/ecosystems/c/celo.toml
Yob is a ticket booking Dapp that offers secure, fast, and decentralized transactions for booking tickets online. It eliminates the need for intermediaries and ensures data privacy, reducing fraud and enabling efficient ticketing.
The purpose of this Yob is to provide a platform for the sale and purchase of event tickets, Users can purchase tickets for events through the smart contract and their purchases will be recorded and tracked.
=> Yob-Ticketing-dapp added

data/ecosystems/c/celo.toml
For gitcoin 
[repo]
url = https://github.com/bezata/NFTHUB-Arthouse
=> Added repo

data/ecosystems/x/xdc.toml
expanding on the list of projects and developers that reside o the xdc network
=> expanding the xdc developer& project  list 

data/ecosystems/e/ethereum.toml, data/ecosystems/f/fenix.toml
Just watched @mariashen give a talk at BuildETH. Following up 🫡
=> Add FENIX ecosystem

data/ecosystems/c/chia.toml
Added in a lot of missing repos to the chia.toml.
=> Update chia.toml with 96 missing repos

data/ecosystems/t/ton.toml
Add:
https://github.com/ilyjs/ton
https://github.com/tact-lang/awesome-tact
https://github.com/ton-play/tonplay-unity-sdk
https://github.com/ton-play/tonplay-python-sdk
https://github.com/ton-play/tonplay-telegram-bot
https://github.com/ton-play/tonplay-unity-react-wrapper
https://github.com/ton-play/tonplay-typescript-sdk
https://github.com/AlexGor-dev/Top-Wallets
=> Update TON repos

data/ecosystems/c/celo.toml
This is the repo for Twilight for women build celo Hackathon
=> Update for champions

data/ecosystems/c/canto.toml
- adding more canto repositories from plex and bharvest
=> Add more Canto repositories 

data/ecosystems/a/arda.toml, data/ecosystems/m/multiversx-elrond.toml
Added:
- Arda;
- new repos from ecosystem;
=> added Arda and update for May

data/ecosystems/c/celo.toml
$250 for most impactful project (Qwame, Crowdfunding platform for African scientists) for the Women in Celo Hackathon.
Included my repo in the `celo.toml` file.
=> Women in Celo Hackathon

data/ecosystems/c/celo.toml
Won 500 cUSD in LATAM DeveloperWeek 2023.
Repo URL: https://github.com/Riya500-git/DeveloperWeek-Hack
=> New changes

data/ecosystems/a/avalanche.toml
=> add precompile-evm to avalanche ecosystem

data/ecosystems/i/internet-computer.toml
I added to internet-computer.toml for June
=> Additions to internet-computer.toml for June

data/ecosystems/a/avalanche.toml, data/ecosystems/s/struct-finance.toml
Adds Struct Finance
- Created  `struct-finance.toml` in data/ecosystems/s
- Added `Struct Finance` to `avalanche.toml`
=> Add Struct Finance to Avalanche Sub Eco

data/ecosystems/e/eos.toml
We've been meaning to contribute to your awesome reporting mechanisms for a while now, and finally got the nudge by other actors in the EOS ecosystem to contribute some of our projects here. 
Listed in this PR is repositories from both the @greymass and @wharfkit organizations, both which our team develops for.
We have included all of our projects that are either:
- Products (Wallets, Applications, Services)
- Developer Tools (SDKs, Utilities, etc)
There's a lot to add, which represents multiple years worth of work, so apologies in advance for doing this in bulk. 
Please let me know if you have any questions.
=> Adding Greymass contributions to the EOS ecosystem

data/ecosystems/g/gitpoap.toml
=> Add GitPOAP

data/ecosystems/s/soneso.toml, data/ecosystems/s/stellar.toml, data/ecosystems/s/stronghold.toml
The Stellar ecosystem is undergoing some big growth, spurred on by the upcoming Soroban smart contracts platform. I've added some ecosystem organizations and repositories that were previously missing.
It's my first contribution to this repo, so please let me know if there's anything that needs to be changed or done differently. Thanks!
=> Adding a few organizations and repos for the Stellar ecosystem

data/ecosystems/i/internet-computer.toml
Additions to internet-computer.toml
=> Additions to internet-computer.toml

data/ecosystems/c/cardano.toml
DirecteEd repositories containing all smart contracts, wallet connect and nft gating functionalities.
=> feat: add DirectEd repos

data/ecosystems/a/aleph-zero.toml, data/ecosystems/a/arbitrum.toml, data/ecosystems/a/astar-network.toml, data/ecosystems/a/avalanche.toml, data/ecosystems/g/gear-tech.toml, data/ecosystems/k/kodadot.toml, data/ecosystems/m/manta-network.toml, data/ecosystems/m/mantle.toml, data/ecosystems/m/moonbeam.toml, data/ecosystems/m/moonriver.toml, data/ecosystems/o/optimism.toml, data/ecosystems/p/polygon.toml, data/ecosystems/s/scroll.toml, data/ecosystems/u/unique-network.toml, data/ecosystems/z/zksync.toml
We are deploying NFT Explorer on other L2s in Ethereum too
More to verify are here on alpha deployment - https://canary.kodadot.xyz/
=> Add Kodadot to various L2 subecosystems

data/ecosystems/t/ton.toml
Hey,
We have rebranded our product to HipoFinance. Just wanted to reflect it in this repository.
Thanks
=> Rename StakeHipo to HipoFinance and add new repositories

data/ecosystems/c/cardano.toml
=> Update cardano's data with some well-known projects / organizations.

data/ecosystems/c/celo.toml, data/ecosystems/c/conflux-network.toml, data/ecosystems/e/eos.toml, data/ecosystems/e/ergo-developer-tooling.toml, data/ecosystems/e/ergo-education.toml, data/ecosystems/e/ergo-hackathons.toml, data/ecosystems/e/ergo.toml, data/ecosystems/f/flow-community.toml, data/ecosystems/h/holyheld.toml, data/ecosystems/i/internet-computer.toml, data/ecosystems/m/machinefi.toml, data/ecosystems/m/multiversx-elrond.toml, data/ecosystems/s/solana.toml, data/ecosystems/t/tezos.toml, data/ecosystems/t/ton.toml, src/main.rs
The workflow should yield an error when it encounters duplicate repos within the same ecosystem toml file
=> check duplicate repos on validation step

data/ecosystems/a/archway-network.toml, data/ecosystems/c/cosmos.toml
Hello! I want add Archway Network
=> Add Archway Network to taxonomy

data/ecosystems/t/ton.toml
Added new repositories
Removed non-TON related
Updated org list
Sorted repos & orgs
=> Update TON Ecosystem

data/ecosystems/s/starknet.toml
This PR updates the Starknet repos in the crypto-ecosystem repo.
=> :tada: Update Starknet Repos

data/ecosystems/c/canto.toml
- added canto dev team orgs
- added repos
=> Add more canto orgs and repos

data/ecosystems/m/mina-protocol.toml, data/ecosystems/p/palladians.toml
Adding Palladian repositories to `mina-protocol.toml`.
=> Add Mina Protocol repos

data/ecosystems/a/avalanche.toml
Hey @eherrerosj, I have added a bunch of new repos from the Avalanche ecosystem.
=> Added new Avalanche ecosystem repositories

data/ecosystems/s/starknet.toml
Adding some missing organizations and repositories for Starknet ecosystem.
=> 📝 update starknet ecosystem: add some missing organizations and repos

data/ecosystems/p/polkadot-developer-heroes.toml, data/ecosystems/p/polkadot.toml
Add repos and org related to the [Polkadot Developer Heroes Programme](https://wiki.polkadot.network/docs/dev-heroes) as a sub-ecosystem of Polkadot
=> Add Polkadot Developer Heroes Programme

data/ecosystems/k/kaupang-dx.toml, data/ecosystems/m/mina-protocol.toml, data/ecosystems/p/proto-kit.toml
This is a new PR that fixes the previous merge conflicts in the now closed original [PR](https://github.com/electric-capital/crypto-ecosystems/pull/614).
=> Add new Mina ecosystem repositories

data/ecosystems/a/aptos.toml, data/ecosystems/a/avalanche.toml, data/ecosystems/m/move.toml, data/ecosystems/m/movement.toml, data/ecosystems/s/sui.toml
Include Movement ecosystem
Include Movement as a sub ecosystem of Avalanche, Move, Aptos and Sui
=> Include Movement ecosystem

README.md
Hey Everyone! 👋
Phil here - this is a PR I've wanted to make for a while. Every day I see the tireless work of the brilliant @eherrerosj in helping people contribute data to this amazing resource. I have myself also tried to help by supporting new contributors with understanding how this repo works.
Therefore, this weekend I decided finally to make this PR. **Its core goal is to save Enrique time**. 😁
From the PRs I have seen, most people have no idea how to contribute to this repo. Even long-term contributors are often doing it wrong (e.g. adding repos where they should be adding just organizations etc). 
This PR is as such an attempt to help make it easier for people to understand exactly how this repo works and how they can contribute to it. I have structured it as an ELI5 guide. The …
=> Add detailed step-by-step guide on how to contribute

data/ecosystems/a/arbitrum.toml, data/ecosystems/m/mimicry.toml, data/ecosystems/p/polygon.toml, data/ecosystems/v/voltz-protocol.toml, src/main.rs
Hey Everyone! 👋
Phil here! This PR builds on https://github.com/electric-capital/crypto-ecosystems/pull/668. Please see it first for context on this PR too.
I noticed that some of @eherrerosj's comments are ones on simple lints (e.g. https://github.com/electric-capital/crypto-ecosystems/pull/629#discussion_r1385083349). This PR therefore aims to save Enrique time by spotting those errors automatically and displaying them to contributors with a clearly actionable message. With a big influx of PRs coming in before Christmas, these extra checks will save a lot of time.
I've added the extra validation rules here in the same style as this repo uses for validating duplicate repos and sub-ecosystems, so that the code style remains the same.
-- Phil
=> Add title validation to CI

data/ecosystems/m/mina-protocol.toml
Adding new repositories that are from the new Mina Navigators Program!
=> New Mina Navigators Program Repositories

data/ecosystems/r/radix-dlt.toml
Transaction Manifest Builder is a tool to help you build complex multi-step transactions on Radix DLT
=> Add tmbuilder reto to Radix DLT

data/ecosystems/b/bitfinity-network.toml, data/ecosystems/d/dfinity-lab.toml, data/ecosystems/d/dfinity-sandbox.toml, data/ecosystems/d/dfinity.toml, data/ecosystems/i/internet-computer.toml, data/ecosystems/j/junobuild.toml, data/ecosystems/m/mate-sol.toml, data/ecosystems/o/octopus-network.toml, data/ecosystems/q/queriodao.toml, data/ecosystems/q/quezarhq.toml, data/ecosystems/t/terablock.toml, data/ecosystems/u/umi.toml
=> update icp ecosystem

data/ecosystems/g/give-cup.toml, data/ecosystems/l/locki-io.toml, data/ecosystems/m/multiversx-elrond.toml, data/ecosystems/m/mvx-tkyc.toml
Added participants at xDay MultiversX Hackathon
=> hackathon participants add

data/ecosystems/m/mina-protocol.toml
This PR adds a new set of Mina hackathon repositories.
=> New Mina Hakathons Repos

data/ecosystems/p/pfp-dao.toml, data/ecosystems/p/polygon.toml
Add the PFP-DAO to polygon ecosystem
=> Add PFP DAO to polygon

data/ecosystems/s/solana.toml
Added a decent amount of repos that were missing, roughly 2870 repos.
=> Add missing Solana repos dec12

data/ecosystems/8/88x.toml, data/ecosystems/a/archly.toml, data/ecosystems/a/axelar-network.toml, data/ecosystems/c/cedro.toml, data/ecosystems/c/cora.toml, data/ecosystems/i/interswap.toml, data/ecosystems/j/jaypigs.toml, data/ecosystems/j/junkyard.toml, data/ecosystems/l/lync.toml, data/ecosystems/m/mint-dao.toml, data/ecosystems/n/nexa.toml, data/ecosystems/p/peanut.toml, data/ecosystems/p/prime.toml, data/ecosystems/s/sugarcane.toml, data/ecosystems/u/unfungibles.toml, data/ecosystems/u/unison.toml
Added in `sub_ecosystems` for Axelar network
=> Add Axelar Ecosystems

data/ecosystems/a/aave.toml
Most of Aave modern developpement is done via Aave Improvement Proposals, Coordinated by BGD Labs Aave DAO service provider.
Added Governance V2 and Governance V3 AIPs repo allowing to track most protocol-related activity.
=> Track Aave DAO dev activity

data/ecosystems/c/celo.toml
Added a Celo ecosystem repos that were missing, approximately 172 repos.
=> Adding missing Celo repos Dec 13, 2023

data/ecosystems/c/cosmos.toml, data/ecosystems/o/osmosis.toml, data/ecosystems/q/quasar-finance.toml
Added Quasar Finance as a Cosmos sub_ecosystem
=> Add Quasar Finance to Cosmos

data/ecosystems/h/hedera.toml
Token Creator, Locker, Burner, Logo, Airdrop, Vesting, Launchpad For Hedera.
=> ADD DaVinciGraph.

data/ecosystems/h/hedera.toml
added CelebratewithHedera proj to hedera.toml
=> added proj to hedera.toml

data/ecosystems/h/hedera.toml
=> add hash and slash repos

data/ecosystems/s/scroll.toml
Adds Scroll projects for November and Dec '23. Most from coming from ETHIndia '23 and manually reviewed for contract deployment and verification on Scroll block explorers.
=> Scroll Ecosystem Update

data/ecosystems/h/hedera.toml
=> repo added for spheraworld

data/ecosystems/s/solana.toml
Added [Nonci](https://nonci.xyz) API and SDK repos to Solana
=> Add Nonci to Solana

data/ecosystems/s/solana.toml
Added the [Revokin](https://revokin.com) repo to Solana
=> Add Revokin to Solana

data/ecosystems/s/solana.toml
Added : 
- Solana Kit, IKnowSpots & BreezyMint
- Added further missing projects
=> Added IKS, Breezymint and Solana Kit

data/ecosystems/a/avalanche.toml
I added a few more repositories that we received from Constellation hackathon submissions. I have appended them at the end as I saw you sorted the list recently and added more repos.
cc @eherrerosj
=> Add avalanche repos from Constellation hackathon

data/ecosystems/s/sui.toml
Added the [Sui zkLogin demo](https://docs.sui.io/concepts/cryptography/zklogin/zklogin-example) repo to Sui
=> Add Sui zklogin demo

data/ecosystems/b/base.toml, data/ecosystems/v/voodoo-trade.toml
Project- Voodoo Trade
Website- https://voodoo.trade
Defi Llama- https://defillama.com/protocol/voodoo-trade
Category- Decentralized perps, DEX
=> Add Voodoo Trade (base chain)

data/ecosystems/a/aori.toml, data/ecosystems/a/arbitrum.toml, data/ecosystems/a/avalanche.toml, data/ecosystems/b/bnb-chain-bsc.toml, data/ecosystems/o/optimism.toml, data/ecosystems/p/polygon.toml
hi, adding aori.io repositories
=> add aori.io repos

data/ecosystems/p/polygon.toml
Add the projects that Clamp submitted for the EthGlobal hackathons
1. OneSave for EthIstanbul 2023
2. OneKYC for EthIndia 2023
=> Add Clamp's Hackathon Projects

data/ecosystems/s/starknet.toml
This PR adds Snapshot and Checkpoint main repositories
=> Add Snapshot and Checkpoint main repositories

data/ecosystems/s/starknet.toml
Hello, thanks in advance for the quick review.
=> ODAx Add Starknet Ecosystem

data/ecosystems/h/helium.toml
Adding my own Helium-related project
=> add lthiery/hnt-explorer to helium ecosystem

data/ecosystems/s/starknet.toml
https://starkexport.xyz
Effortlessly effort Starknet transactions to CSV, XLSX, JSON and more
https://github.com/mylastwanto/StarkExport
=> Add StarkExport to Starknet

data/ecosystems/c/chiliz.toml, data/ecosystems/s/sui.toml
Links were edited and pull request was created again with the updated branch
=> Adding Rise In bootcamp community repos

data/ecosystems/s/starkdefi.toml, data/ecosystems/s/starknet.toml
=> Update Starknet ecosystem

data/ecosystems/d/diode.toml, data/ecosystems/m/moonbeam.toml
Adds Diode Ecosystem. They previously had their own chain but they are building exclusively on Moonbeam now.
=> Add Diode Ecosystem

data/ecosystems/z/zksync.toml
a bot for check info of special wallet on zksync
=> Add more repo on zksync

data/ecosystems/s/starknet.toml
add https://github.com/shepf/starknet_study
Starknet CSDN Learning Column and Example Demo
=> Update starknet.toml，add https://github.com/shepf/starknet_study

data/ecosystems/n/node-guardians.toml, data/ecosystems/s/starknet.toml
Add [Starknext](https://github.com/swiiny/starknext) template and [Node Guardians](https://github.com/Nodeguardians) to Starknet ecosystem
=> Add Node Guardians to Starknet ecosystem

data/ecosystems/s/starknet.toml
=> My github repos included

data/ecosystems/p/polygon-zkevm.toml
Add KEOM protocol contracts repo
=> Update polygon-zkevm.toml: Add KEOM protocol contracts repo

data/ecosystems/s/starknet.toml
Update starknet.toml with mississippi mini repo
=> Update starknet.toml with mississippi mini repo

data/ecosystems/z/zksync.toml
zksync network uses dex of ve33 model
=> zksync network uses dex of ve33 model

data/ecosystems/a/avalanche.toml
added a few more missing repos @eherrerosj, thank you 🙏🏽
=> Add repos to avalanche.toml

data/ecosystems/s/starknet.toml
=> Add Ekubo Protocol to starknet.toml

data/ecosystems/s/starknet.toml
Added Exothium Organization, Exoworld, Phaser-Starknet-BoilerPlate and Website
=> Update starknet.toml with Exothium's organization and repos

data/ecosystems/i/idarkstudio.toml, data/ecosystems/i/internet-computer.toml, data/ecosystems/s/starknet.toml
- Added Loka Mining, TaxLint, Faceless, PWS, SafeNote, InfinitiNote, Hashkey, Xtreamly Team, Arth App, ICP VirtuaSeal, VFans-IC, Invoice Canister ICP, IC Data Platform, Pado, Uniot
=> Add Internet Computer Grant/Ecosystem Projects

data/ecosystems/s/starknet.toml
This PR updates the Starknet repos in the crypto-ecosystem repo; taking into account duplicated repos.
=> :tada: update general starknet repos

data/ecosystems/z/zkflip.toml, data/ecosystems/z/zksync.toml, zkflip.md
Add zkFlip to zkSync
Add zkFlip to ecosystem/data
=> Add zkflip

data/ecosystems/a/avnu.toml, data/ecosystems/s/starknet.toml
Adding AVNU organization and public repositories.
=> :sparkles: Add AVNU org and repositories starknet.toml

data/ecosystems/s/starknet.toml
Add Starknet repos:
https://github.com/satyambnsal/starknet-dapp
https://github.com/satyambnsal/cairo-smart-contracts
=> Update Starknet.toml -> Add StarkVoice and cairo-contracts

data/ecosystems/c/carbonable.toml, data/ecosystems/s/starknet.toml
Update Starknet.toml -> Add Carbonable and Carbonable-labs public repos
=> Update Starknet.toml -> Add Carbonable and Carbonable-labs repos

data/ecosystems/s/starknet.toml
add https://github.com/kylifish0100/xyzDEX
Uniswap V2 fork implementation in Cairo
=> Update Starknet.toml -> Add xyzDex repo

data/ecosystems/a/antelope.toml, data/ecosystems/e/eos.toml, data/ecosystems/l/libre.toml, data/ecosystems/p/proton.toml, data/ecosystems/t/telos.toml, data/ecosystems/u/ultra.toml, data/ecosystems/w/wax.toml
- added libre ecosystem 
- reorganized edenia projects under corresponding ecosystems
- added tikuna project - an ethereum foundation grant
=> Add and Organize edenia projects

data/ecosystems/a/anoma.toml, data/ecosystems/c/cosmos-network.toml, data/ecosystems/f/filecoin.toml, data/ecosystems/p/polkadot-network.toml, data/ecosystems/s/starknet.toml
Adding zondax contributions to Filecoin, Anoma, Cosmos, Polkadot and Starknet ecosystems.
=> Add zondax contributions

data/ecosystems/n/nicera.toml, data/ecosystems/s/starknet.toml, data/ecosystems/s/starkware.toml
Update Starknet.toml -> add Carbonable in sub
Update Starkware.toml -> add Carbonable in sub
update Starknet.toml -> add Nicera and repos
add Nicera.toml -> add Nicera and repos
=> add_nicera

data/ecosystems/8/88x.toml, data/ecosystems/a/artizyou-inc.toml, data/ecosystems/a/astarter.toml, data/ecosystems/a/axo.toml, data/ecosystems/c/cedro.toml, data/ecosystems/h/headline-design.toml, data/ecosystems/h/helixstreet.toml, data/ecosystems/j/jambo-network.toml, data/ecosystems/j/jaypigs.toml, data/ecosystems/j/junkyard.toml, data/ecosystems/l/lync.toml, data/ecosystems/m/magic-land.toml, data/ecosystems/m/muesli-swap.toml, data/ecosystems/n/nexa.toml, data/ecosystems/p/parrot-defi.toml, data/ecosystems/r/rootsoft.toml, data/ecosystems/s/slonigiraf.toml, data/ecosystems/s/sugarcane.toml, data/ecosystems/t/tpfs.toml, data/ecosystems/u/unfungibles.toml, data/ecosystems/u/unison.toml, data/ecosystems/z/zengate-global.toml, src/main.rs
Hey Everyone! 👋
Phil here! This PR builds on https://github.com/electric-capital/crypto-ecosystems/pull/668 and https://github.com/electric-capital/crypto-ecosystems/pull/669. Please see #668 first for context on this PR too.
This PR is aimed at saving time manually PRs that have added empty ecosystems, such as here: https://github.com/electric-capital/crypto-ecosystems/pull/657#pullrequestreview-1740657748. 
The validation logic here is correct and will reject any PR which has an empty ecosystem in a file (defined as having no repos, organizations or sub-ecosystems). The CI is currently failing only because there are files which do not adhere to this rule currently. I have not removed these in this PR yet since it is a destructive action. Before merging, we should delete them though. …
=> Add ecosystem validation to CI

data/ecosystems/e/easi-dao.toml, data/ecosystems/h/hedera.toml
A Hedera DAO. Verified by The Hashgraph Association
=> Add easiDAO

data/ecosystems/e/express-do.toml, data/ecosystems/s/starknet.toml
Tried creating a new chain with cairo language: Express Chain
=> Add Express chain

data/ecosystems/z/zksync.toml
A payment gateway smart contract for managing transaction fees using zkSync. This repository contains the source code for the Paymaster contract, allowing users to pay fees for transactions using an ERC-20 token.
=> Update zksync.toml - add zkSync-paymaster

data/ecosystems/m/mochi.toml, data/ecosystems/s/starknet.toml
Tried to create an ecosystem with Cairo
=> Mochi Chain Ecosystem

data/ecosystems/s/starknet.toml
StarkMint is a platform on Starknet that enables users to create ERC20 tokens and ERC721 NFTs in a no-code manner. Would appreciate if this PR is accepted.
=> StarkMint added to the list

data/ecosystems/n/noir-lang.toml
Add the [Noir benchmarking repository](https://github.com/Savio-Sou/noir-benchmarks) Maddiaa and I have been working on to the Noir ZK language ecosystem.
=> Add Noir Benchmarks

data/ecosystems/d/dojo-engine.toml
adding repos from Dojo Holiday Game Jam
=> add game jam repos

data/ecosystems/a/algorand.toml
Personal EVM projects are in Algorand file.
They were never developed for nor deployed on Algorand.
=> RM projects from Algorand

data/ecosystems/c/chroma.toml
- Adds two repo's: [reflex](https://github.com/chromaxyz/reflex) and accompanying [reflex-template](https://github.com/chromaxyz/reflex-template), a free and open source Solidity framework for upgradeable modularized applications.
=> Add Chroma

data/ecosystems/c/clave.toml
=> Update Clave Repositories

data/ecosystems/n/nounsdao.toml
[nouns-anonymous-voting](https://github.com/aragonzkresearch/nouns-anonymous-voting) is a private voting research project collaboratively conducted by Aragon ZK Research and Aztec Labs for NounsDAO as a part of the [NounsDAO Private Voting Research Sprint](https://hackmd.io/@el4d/BkDBV1Pso).
Read the [research report](https://blog.aragon.org/announcing-a-proof-of-concept-for-private-voting-in-nouns-dao/) for more details.
=> Add nouns-anonymous-voting to NounsDAO

data/ecosystems/a/alien-valley.toml, data/ecosystems/h/hypercore-one.toml, data/ecosystems/h/hypercore-team.toml, data/ecosystems/i/ignition-pillar.toml, data/ecosystems/z/zenon-hub.toml, data/ecosystems/z/zenon-org.toml, data/ecosystems/z/zenon-tools.toml, data/ecosystems/z/zenon.toml
Update `zenon.toml` information and add sub-ecosystems to taxonomy.
=> Zenon Update and Sub-ecosystems Additions

data/ecosystems/m/magicblock.toml, data/ecosystems/s/solana.toml
=> :memo: Update repos and add Magicblock

data/ecosystems/c/cardano.toml
Add Work With Cardano org and Xogmios repo
=> Add Work With Cardano

data/ecosystems/p/phala-network.toml
Add Sub-Ecosystems to Phala Network.
=> Update Phala Network and add Sub-Ecosystems

data/ecosystems/n/near.toml, data/ecosystems/u/unifat.toml
UniFat(https://github.com/unifat-xyz), the first platform on Near to integrate Inscription LaunchPad and Inscription Games.
NRC404 protocol on Near, a tribute to ERC404, repo:https://github.com/unifat-xyz/NRC404
=> add unifat-xyz and nrc404 repo

data/ecosystems/o/ora.toml
- Rename from "HyperOracle" to "ORA" due to rebranding
- Update repo and org names in ORA
- Add ORA as sub-ecosystem of Ethereum
=> Update ORA ecosystem

data/ecosystems/t/topos.toml
This PR adds the core Topos Protocol repositories that Topos community members work on, as well as all of the known grant recipient repos and tangential repos specific to the Topos ecosystem.
=> Add Topos Ecosystem contributions

data/ecosystems/p/polkadot-network.toml
We would like to update ParaSpell links. Thank you.
With kind regards,
Team ParaSpell
=> Update ParaSpell✨ links

data/ecosystems/e/ethereum-consensus.toml
This PR updates the list with repositories which include the TypeScript ecosystem surrounding Lodestar and its major dependencies. These repositories contribute to the success of Lodestar and Ethereum consensus in TypeScript.
=> Update ChainSafe repos on ethereum-consensus.toml

data/ecosystems/c/cardano.toml
zkFold is a company developing scalability products for the Cardano blockchain. Please, add our repositories to the list. Thank you.
=> Add zkFold organization and repositories

data/ecosystems/g/general.toml
Add [web-bip39](https://github.com/hujiulong/web-bip39) to general.toml
=> Add web-bip39 to general.toml

data/ecosystems/s/stellar.toml
Hey hey! Just adding a new Stellar dApp tutorial here!
For ease of reviewing, the relevant Stellar code for payments is here! under this directory! https://github.com/platonicsocrates/payments-dapp-tutorial/tree/master/src/components/send-payment
E.g.
https://github.com/platonicsocrates/payments-dapp-tutorial/blob/master/src/components/send-payment/confirm-payment.tsx
https://github.com/platonicsocrates/payments-dapp-tutorial/blob/master/src/components/send-payment/connect-wallet.tsx
https://github.com/platonicsocrates/payments-dapp-tutorial/blob/master/src/components/send-payment/index.tsx
=> add stellar dapp tutorial

data/ecosystems/s/starknet.toml
Added [Rising-Revenant](https://github.com/grugslair/Rising-Revenant) to the startknet ecosystem
=> Added Rising-Revenant repo to starknet

data/ecosystems/c/citrea.toml
We've just open-sourced our Citrea's code, and then I saw this repository. Wanted to say thanks a lot for such community work, and also added our newest repo :)
=> Add chainwayxyz/citrea

data/ecosystems/s/starknet.toml, data/ecosystems/w/walnut.toml
Added [Walnut](https://github.com/walnuthq) to Starknet Ecosystem
=> Add Walnut to Starknet Ecosystem

data/ecosystems/f/flashbots.toml
This pull request adds the Flashbots project to the Ethereum ecosystem. Flashbots is a platform that aims to mitigate the negative impact of miner-extractable value (MEV) on Ethereum.
=> Add Flashbots to Ethereum ecosystem

data/ecosystems/a/AO-Computer.toml, data/ecosystems/a/arweave.toml
V2
1. Create AO-Computer taxonomy
2.Add AO Computer to Arweave Sub Ecosystems
3.Add Repos to Arweave
=> Arweave-Update/AO Computer Addition

data/ecosystems/t/topos-ecosystem.toml
This repository will end up holding smart contracts for the Topos community's certification program.
=> Add the certification contracts repo.

data/ecosystems/s/sphinx-protocol.toml, data/ecosystems/s/starknet.toml
Add Sphinx protocol integration on Starknet
Integrated the Sphinx protocol with Starknet. Check out the SphinxDB repositories for more details: https://github.com/orgs/SphinxDB/repositories
=>  Add Sphinx protocol

data/ecosystems/z/ziptos.toml
Update Ziptos Ecosystem on Aptos
=> Update Ziptos Ecosystem

data/ecosystems/m/moonbeam.toml
=> Moonbeam Mid Year Updates

data/ecosystems/s/starknet.toml
Add TxGamesStudio - TxSpaces repo
=> Add TxGamesStudio - TxSpaces repo

data/ecosystems/s/starknet.toml
Add repositories related to Starknet on Bitcoin effort.
Mainly the Bitcoin Circle STARK verifier repo and few additional ones.
Also adding STWO new prover.
=> 📝 add starknet on bitcoin related repositories

data/ecosystems/s/starknet.toml
Add Data Processor related public repositories that utilize Cairo VM
=> Add herdotus.dev repos on `starknet.toml`

data/ecosystems/s/starknet.toml
Hello,
I updated the starknet.toml file with more repos from the project I maintain. Also I updated the main repo that was renamed a while ago.
=> Ad Apibara repos to starknet.toml

data/ecosystems/s/starknet.toml
[repo](https://github.com/starknet-io/types-js )
[npm](https://www.npmjs.com/package/@starknet-io/types-js)
=> Add types-js to  starknet.toml

data/ecosystems/s/starknet.toml
update repos of nicera on starknet
=> Update starknet.toml with Nicera repos

data/ecosystems/w/wormhole.toml
=> add wormhole labs repos

data/ecosystems/c/c3-exchange.toml, data/ecosystems/h/hashflow.toml, data/ecosystems/j/jupiter-exchange.toml, data/ecosystems/m/magpie.toml, data/ecosystems/m/mayan-finance.toml, data/ecosystems/p/portal-bridge.toml, data/ecosystems/p/pyth-network.toml, data/ecosystems/w/wormhole.toml
=> Add / Update various

data/ecosystems/b/bagpipes.toml, data/ecosystems/m/moonbeam.toml
=> add bagpipes 

data/ecosystems/s/starknet.toml
Adds the Starknet ABI package for encoding and decoding Starknet contract calls and events: https://github.com/NethermindEth/starknet-abi
=> feat: add starknet-abi package

data/ecosystems/k/karnot.toml, data/ecosystems/m/madara.toml, data/ecosystems/s/starknet.toml
- Added Madara repos.
- Added Karnot repos.
- Added some other repos from Moonsong Labs related to madara.
- Added one repo from abdelstark related to madara
=> Updated : Added repos related to Karnot and Madara

data/ecosystems/r/realm-of-ra.roml, data/ecosystems/r/realm-of-ra.toml, data/ecosystems/s/starknet.toml
RealmOfRa is developing a pilot project for it's on-chain gaming studio on Starknet
=> feat: added RealmOfRa

data/ecosystems/e/expectium.toml, data/ecosystems/s/starknet.toml
Adding Expectium Protocol, https://expectium.io/
=> Adding Expectium Protocol

data/ecosystems/a/aptos.toml, data/ecosystems/a/avex-defy.toml
=> Added Avex Defy

data/ecosystems/a/aptos.toml, data/ecosystems/s/supervillain-labs.toml
Add Supervillain labs for Aptos ecosystem
=> feat: Add Supervillain labs

data/ecosystems/a/algorand.toml
Removed 21 repos that don't mention Algorand
=> Update algorand.toml: Remove repos that never mention Algorand

data/ecosystems/b/base.toml
This PR updates the previous metadata for Base, adding new sub-ecosystems and repos.
=> Update sub-ecosystems and add new repos for Base

data/ecosystems/b/bitcoin.toml, data/ecosystems/c/cosmos-network.toml, data/ecosystems/s/surge.toml
**Added Surge ecosystem as a sub-ecosystem to Bitcoin, along with our repository link.**
Surge is a Metalayer for Bitcoin Scaling, You can find more details, [here](https://surge.build/).
Thanks for aggregating all the ecosystem and community work! 😊
=> Added Surge under Bitcoin Ecosystem

data/ecosystems/s/starknet.toml
Hey, this is Omar Espejel from the Starknet Foundation.
Happy to make any necessary edits.
=> Add starknet repos up to 2024-10-12

data/ecosystems/h/hyperlane.toml
Astraly, bertux/Arthera, Bootnode, Forma, Glacis, Henez, Karak, Lukso, Many Things/Mitosis, Polkachu, Superbridge, Toucan
=> add Q3 2024 Hyperlane ecosystem contributors

data/ecosystems/s/solana.toml
add francis-codex solana-based repos
=> add francis-codex solana-based repos

data/ecosystems/s/sui.toml
Adds new repo: `polymedia-bidder`
Removes renamed repo: `gotbeef` (now `polymedia-gotbeef`)
=> Update polymedia repos in sui.toml

data/ecosystems/s/sui.toml
Adding missing interest-protocol repos and josemvcerqueira repos to Sui
Thanks!
=> :sparkles: feat: adding miss repos

data/ecosystems/s/solana.toml
A few more Solana repositories.
=> Add solana repositories

data/ecosystems/k/kaia.toml
- Added more open source contributions from the community to Kaia ecosystem
=> Updated Kaia ecosystem with more community open source repositories

data/ecosystems/s/solana.toml
Added Gator-RR Loyalty Program Repo
=> Added Gator-RR Loyalty Program Repo

data/ecosystems/a/aptos.toml
I am adding my project Hospital Management repo git hub link in the aptos.toml file
=> adding hospital managemnt repo

data/ecosystems/s/solidity.toml
Add the formal verification tool https://github.com/formal-land/coq-of-solidity to solidity.toml
=> Add coq-of-solidity to solidity.toml

data/ecosystems/h/hedera.toml
Adding GRELF project to hedera.toml
=> Add GRELF to hedera.toml

data/ecosystems/b/base.toml
Updates Base with additional metadata
=> Update metadata for Base

data/ecosystems/s/starknet.toml
Grug's Lair Gaming Studio (organization) added to Starknet Ecosystem. 
Games:
- Rising Revenant
- Blob Arena
=> Add Grug's Lair Org & Repo

data/ecosystems/a/axol.toml
axol.io is a staking-provider of FOSS-first LATAM Nodes and Ecosystem development. We collaborate on all things FOSS.
=> Add axol.toml

data/ecosystems/b/bonzo-finance, data/ecosystems/h/hedera.toml
=> Bonzo Finance to Hedera Ecosystem

data/ecosystems/c/cosmos-network.toml
Add Elys Network name to toml file and remove deprecated Elys repos
=> Add Elys Network to cosmos-network.toml

data/ecosystems/t/tapestry.toml
=> add tapestry to directory

data/ecosystems/m/maker.toml, data/ecosystems/p/powerhouse.toml
Hey guys,
I've added the makerdao ses core unit group repositories to the Maker ecosystem, but also added Powerhouse as Subecosystem. I've put Powerhouse into a separate ecosystem because its a spin off of the MakerDAO SES Core Unit and not only part of the Maker. I'll add Powerhouse soon to other ecosystems too.
=> feat: added repositories of makerdao-ses and powerhouse

data/ecosystems/p/paladin.toml, data/ecosystems/s/solana.toml
Twitter: https://x.com/paladin_solana
=> Adding Paladin Bladesmith

data/ecosystems/s/solana.toml
add my solana related repositories
=> add solana repos

data/ecosystems/h/hyperweb.toml
adding [Hyperweb](https://github.com/hyperweb-io) — built by [Cosmology](https://cosmology.zone) team 
thank you 🙏🏻
=> add hyperweb ecosystem

data/ecosystems/c/celo.toml
Added a Celo ecosystem repos that were missing
=> Adding missing Celo repos Oct 22, 2024

data/ecosystems/c/cosmos-network.toml, data/ecosystems/h/hypersign-protocol.toml
Requesting to add Hypersign protocol.
=> Added hypersign protocol to the taxonomy

data/ecosystems/s/stacks.toml
Several additional Stacks repos added. Ran `make sort` this time ;)
=> Adding additional Stacks repos from builders

data/ecosystems/u/union.toml
fixing a mixup in [union.toml](https://github.com/electric-capital/crypto-ecosystems/blob/master/data/ecosystems/u/union.toml).
It contained Union's repos and repos of another org by accident.
=> fix: union.toml

data/ecosystems/a/artemis.toml
- Add Ecosystem for Artemis https://github.com/Artemis-xyz
- Link to https://github.com/Artemis-xyz/dbt repo
=> Add Artemis ecosystem

data/ecosystems/a/aleo.toml
Update: Cleaning up Aleo repositories
=> Update: Cleaning up ANS repos

data/ecosystems/w/weavevm.toml
[WeaveVM](https://wvm.dev) is a sovereign EVM network built towards the goal of solving the EVM storage dilemma with Arweave. It gives the coming generation of high-performance chains a place to settle and store onchain data, without worrying about cost, availability, or permanence.
=> Add WeaveVM

data/ecosystems/p/polkadot-network.toml
this PR adds a new repo with quick start for polkadot developers
=> add polkadot coding repo

data/ecosystems/f/flare.toml
=> Add Flare repos

data/ecosystems/i/ibm-blockchain.toml
Archived content for IBM Blockchain
Split off a separate PR from previously committed record #1754
=> Submit IBM-Blockchain

data/ecosystems/s/savjeecoin.toml
⚠️ For education purposes only. This is by no means a complete implementation and it is by no means secure!
Features
Simple proof-of-work algorithm
Verify blockchain (to prevent tampering)
Generate wallet (private/public key)
Sign transactions
Split off a separate PR from previously committed record #1754
=> submit the SavjeeCoin

data/ecosystems/m/multiversx-elrond.toml
Added MultiversX repo sdk-dapp-liquidity
=> Added MVX repo sdk-dapp-liquidity

data/ecosystems/a/algorand.toml
- Add a few more repos to algorand list
=> add in more pera repos to electric capital algorand list

data/ecosystems/t/txnlab.toml
Add new nfd-sdk repo to list of TxnLab repos (sub-ecosystem of Algorand)
=> Add nfd-sdk to TxnLab repos

data/ecosystems/a/aptos.toml
Added Meme News Factory project
=> Update aptos.toml. Meme News Factory

data/ecosystems/a/aptos.toml
DevFolio Project: https://devfolio.co/projects/tweefi-1cd1
=> feat: add TweeFi to aptos projects

data/ecosystems/a/aptos.toml
Update aptos.toml - Add ADAS: Aptos DefAI Agent Swarm
Metamove hackathon
=> Update aptos.toml - Add ADAS

data/ecosystems/a/aptos.toml
Hackathon project added for Aptos grant
=> Add AutoVox

data/ecosystems/a/aptos.toml
Added Aptos Trip - a project participating in the Metamove AI Hackaton
=> Added Aptos Trip - a project participating in the Metamove AI Hackaton 

data/ecosystems/a/aptos.toml
Added my move ai agent hackathon project repository
=>  Added AgentAGOS Repository in aptos.toml

data/ecosystems/p/polkadot-network.toml
Adding a few repositories that build on Polkadot since the start of this year.
=> add Polkadot focussed repositories

data/ecosystems/a/avalanche.toml
Added the Avalanche Foundation to orgs, and several community repositories.
=> adding repos to avalanche

migrations/2025-04-14T235959_mutations
Adding https://github.com/cryptomalgo/algonoderewards to Algorand
=> Add AlgoNodeRewards to Algorand

migrations/2025-04-17T235959_mutations
Updated the 2025-04-17 mutation file to be added to the repo list
=> Added YAKKL to the repo list

migrations/2025-05-14T002323_mutations
- add [Self Protocol](https://github.com/selfxyz)
- Add Self Protocol as sub ecosystem of Celo
=> Add Self Protocol

migrations/2025-05-30T235959_algorand_updates
=> Adding a new Algorand Repo 

migrations/2025-06-25T015300_add_zk_age_verification, migrations/2025-06-25T030700_add_noir_basics_example
This PR adds my noir_basics_example project to the NoirLang ecosystem.
The project demonstrates how to verify a simple Noir circuit with Solidity using bb as the proving backend. It includes:
- A Noir circuit that checks x * 2 + y == expected, with x private and y, expected public
- Solidity verifier contract (via Foundry)
- JavaScript code to generate and serialize proofs using bb.js
Repository: https://github.com/cypriansakwa/noir_basics_example
If you’re working in open source crypto, submit your repository here to be counted.
=> Add noir_basics_example to NoirLang ecosystem

migrations/2025-06-20T191500_add_private_message_wall, projects/aztec/filozif-private-message-wall.json
This project is built using Noir and tested with Aztec sandbox.
All tests pass and the repository is actively maintained.
=> Add Private Message Wall to Aztec Protocol ecosystem

migrations/2025-06-25T015300_add_zk_age_verification, migrations/2025-06-25T030700_add_noir_basics_example, migrations/2025-06-26T160700_add_private_key_recovery_gate
This PR adds my Noir-based project to the "Noir Lang" ecosystem.
Repository: https://github.com/cypriansakwa/private_key_recovery_gate
- Tags: #zkp #noir #circuit #recovery
- Includes a zero-knowledge recovery circuit using Noir
- Solidity verifier and Foundry tests included
If you’re working in open source crypto, submit your repository here to be counted.
=> Add private_key_recovery_gate to Noir Lang ecosystem

migrations/2025-06-28T104300_add_prove_threshold_policy, migrations/2025-06-29T164100_add_prove_weighted_threshold_compliance
This pull request adds the following repository to the **Noir Lang** ecosystem:
Repository: https://github.com/cypriansakwa/prove_weighted_threshold_compliance
The repository demonstrates a weighted threshold compliance circuit implemented in Noir, with potential applications in zero-knowledge access control and privacy-preserving systems.
- `#zkp`
- `#noir`
- `#threshold`
- `#circuit`
---
If you’re working in open source crypto, submit your repository here to be counted.
=> Add prove weighted threshold compliance to Noir Lang ecosystem

migrations/2025-07-02T152000_add_phala_dstack_projects
Add 3 repos to Phala Network
1. dstack
2. meta-dstack
3. dstack-examples
=> Add dstack repos to Phala Network

migrations/2025-07-04T120500_add_noir_lang_weighted_voting
Adds a new Noir example project for a weighted voting circuit to the "Noir Lang" ecosystem.
Repository: https://github.com/cypriansakwa/noir_weighted_voting_circuit
Tags: #example #zkp #zk-circuit #noir
If you’re working in open source crypto, submit your repository here to be counted.
=> Add noir_weighted_voting_circuit to Noir Lang ecosystem

migrations/2025-07-08T012257_algorand_updates
Added new repo: Algorand Wallet Watcher
=> Added new repo: Algorand Wallet Watcher

migrations/2025-07-15T192300_add-noir_pedersen_commitment
Adds  noir_pedersen_commitment Example Project to the "Noir Lang" ecosystem.
This PR adds a new example project demonstrating Pedersen commitments implemented in Noir, contributing to the growing collection of zero-knowledge proofs in the Noir Lang ecosystem.
Repository: https://github.com/cypriansakwa/noir_pedersen_commitment
Tags: #example #zkp #pedersen_commitment #noir
=> Add noir_pedersen_commitment example to the Noir Lang ecosystem

migrations/2025-07-10T174812_add_zama_protocol_ecosystem
Add [Zama Protocol](https://docs.zama.ai/protocol) as a new ecosystem and add its core repositories.
=> Add Zama Protocol ecosystem and its repos

migrations/2025-07-23T010100_add-noir-private-set-intersection
Adds a new Noir example project demonstrating a private set intersection (PSI) circuit, contributing to the growing "Noir Lang" ecosystem.
Repository: https://github.com/cypriansakwa/noir-private-set-intersection
Tags: #zkp #zk-circuit #noir #aztec #psi
=> Add noir-private-set-intersection project to the Noir Lang ecosystem

migrations/2025-07-27T010400_add-noir-bls12-381-arithmetic
Adds a new Noir example project `noir-bls12-381-arithmetic` to the "Noir Lang" ecosystem.
Repository: https://github.com/cypriansakwa/noir-bls12-381-arithmetic
Tags: #zkp #zk-circuit #noir #aztec #cryptography
=> Add noir-bls12-381-arithmetic project to the Noir Lang ecosystem

migrations/2025-08-21T213700_add-zk-composite-proof-noir
Adds a new Noir example project for a zk composite proof circuit to the "Noir Lang" ecosystem.
Repository: https://github.com/Lynette7/zk-composite-proof-noir
Tags: #zkp #zk-circuit #noir #aztec
=> chore: Add ZK composite Proof circuit to the Noir Lang Ecosystem

migrations/migrations/2025-09-02T233950_add-aibased-protocol
This pull request introduces a new ecosystem and repository entry for the AIBased Protocol. The change updates the migration file to add AIBased as a recognized ecosystem and links to its core protocol repository.
This pull request adds the AIBased Protocol, a project built within the official [Base ecosystem](https://www.base.org/ecosystem).
Ecosystem and repository additions:
* Added AIBased as a new ecosystem in the migration file.
* Registered the aibased-protocol repository with its GitHub URL and labeled it as #protocol and #smart-contracts.
=> add aibased protocol

migrations/2025-09-10T160000_add_metadao_ecosystem
This PR adds the MetaDAO ecosystem to the crypto-ecosystems taxonomy. MetaDAO was entirely missing from the taxonomy despite being a significant and active project in the Solana ecosystem.
MetaDAO is a decentralized autonomous organization focused on futarchy-based governance and prediction markets built on Solana. They have developed substantial infrastructure including:
- **Core Protocol**: Smart contracts and programs for futarchy governance
- **Data Infrastructure**: Indexing, APIs, and data models for prediction markets
- **AMM Integration**: Jupiter integration for decentralized market making
- **Development Tools**: Anchor build verification and setup tools
- **Token Utilities**: Migration and management tools
- **GitHub Organization**: https://github.com/metaDAOproject (48 public …
=> Add MetaDAO ecosystem to crypto-ecosystems taxonomy

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet
- Added Namada Wallet repository under Anoma ecosystem
- Tags: wallet, rust
- Source: https://github.com/anoma/namada-wallet
=> Add Namada Wallet repository to Anoma ecosystem

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet, migrations/2025-10-02T220000_add_more_namada_repos
Added additional Namada repositories under the Anoma ecosystem.
- Added Namada examples repository (#examples, #rust)
Source: https://github.com/anoma/namada-examples
- Added Namada devnet repository (#testnet, #infrastructure)
Source: https://github.com/anoma/namada-devnet
- Added Namada indexer repository (#indexer, #rust)
Source: https://github.com/anoma/namada-indexer
=> Add more Namada repositories (examples, devnet, indexer) under Anoma ecosystem

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet, migrations/2025-10-02T210000_add_namada_repo
- Added Namada core repository
- Added Namada trusted-setup repository
- Tags: protocol, rust, infrastructure
- Sources:
- https://github.com/anoma/namada
- https://github.com/anoma/namada-trusted-setup
=> Add Namada repositories under Anoma ecosystem

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet, migrations/2025-10-03T123000_add_namada_bridge
- Added Namada Bridge repository under Anoma ecosystem
- Tags: bridge, rust
- Source: https://github.com/anoma/namada-bridge
=> Add Namada Bridge repository to Anoma ecosystem

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet, migrations/2025-10-03T130000_add_namada_benchmarks
- Added Namada Benchmarks repository under Anoma ecosystem
- Tags: benchmark, rust
- Source: https://github.com/anoma/namada-benchmarks
=> Add Namada Benchmarks repository to Anoma ecosystem

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet, migrations/2025-10-03T133000_add_namada_governance
- Added Namada Governance repository under Anoma ecosystem
- Tags: governance, rust
- Source: https://github.com/anoma/namada-governance
=> Add Namada Governance repository to Anoma ecosystem

migrations/2025-10-02T150500_add_namada_wallet, migrations/2025-10-02T173000_add_warden_faucet, migrations/2025-10-03T150000_add_namada_explorer_ui
git add 2025-10-03T150000_add_namada_explorer_ui
git commit -m "Add Namada Explorer UI repository to Anoma ecosystem"
git push origin add-namada-explorer-ui
=> Add Namada Explorer UI repository to Anoma ecosystem

migrations/2025-10-04T185100_add_vaarush_digital_inheritance
Add my existing Vaarush 2.0 repository—currently enrolled in the AlgoBharat Hack Series #2—into the Electric Capital crypto-ecosystems taxonomy under Algorand. Vaarush 2.0 provides a blockchain-based digital inheritance management system built on Algorand smart contracts, with features for plan creation, timed asset release, and proof verification. Including this repo ensures all commits to Vaarush 2.0 will be tracked for Algo Git Squad and visible in the Algorand ecosystem listing. Thanks for reviewing!
=> Add Vaarush 2.0 digital inheritance project to Algorand ecosystem

migrations/2025-08-20T235959_algorand_update, migrations/2025-09-28T235959_algorand_update, migrations/2025-10-08T235959_algorand_update
simple voting dapp is submitting.
=> submitting new algorand project
