data/ecosystems/c/chainstack.toml

Add Chainstack -- a blockchain deployment platform similar to Infura
but with multi-protocol support

Add Chainstack

---

data/ecosystems/p/project-serum.toml
data/ecosystems/s/solana.toml

A few projects related to Solana and Serum were missing from their pertaining ecosystem files. I went ahead and added the missing projects to each.
An open question: Solana has multiple partnerships announced [here](https://solana.com/ecosystem) that don't have public GitHub links. I noticed that only git repositories are being added — should I leave these partnerships and engagements out or add in the relevant announcements on other domains?
Many thanks.

Add various projects to the Solana and Serum ecosystem pages

---

data/ecosystems/f/filecoin.toml

There are 39 extras repos in https://github.com/filecoin-shipyard/ that contribute directly to the Filecoin ecosystem

Add filecoin-shipyard to Filecoin github orgs

---

data/ecosystems/i/ipfs.toml

There are 138 extra repos in https://github.com/ipfs-shipyard/ that contribute to the IPFS ecosystem

Added ipfs-shipyard to ipfs orgs

---

data/ecosystems/e/elrond.toml

Our first public product, AshSwap - a stable-swap exchange, is built on Elrond.
We already have testnet version up and running at https://testnet.ashswap.io.
The token faucet at: https://faucet.ashswap.io.
Code can be found at https://github.com/ashswap.

Add AshSwap to Elrond ecosystem

---

data/ecosystems/c/chia.toml

While not directly tied to the crypto, this repo is for automating the monitoring of hard drive health and temperatures, which is useful for farming Chia.

Update chia.toml - add smart farm

---

data/ecosystems/b/bitcoin.toml

The projects either no longer exist or are solely dedicated to an ecosystem other than BTC

remove non-bitcoin projects

---

data/ecosystems/s/starknet.toml

This list is missing starksheet, an open source hybrid between a block explorer a no-code tool and an analytics tools, see https://twitter.com/starksheet

Add Starksheet to the list of Starknet projects

---

data/ecosystems/r/risc0.toml

RISC Zero is an ecosystem built around a RISC-V zkVM allowing verifiable execution of Rust and other general pupose languages. https://www.risczero.com/
This PR adds RISC Zero to the list of tracked ecosystems.

Add ecosystem TOML for RISC Zero

---

data/ecosystems/c/cardano.toml

Added missing Aiken repository URL in Cardano

Update Cardano.toml to include Aiken repository url

---

data/ecosystems/c/celo.toml

This repo holds community contributed repos and examples. heads up @joenyzio @viral-sangani

Adds "celo-examples" gh org holding tutorial repos

---

data/ecosystems/c/celo.toml

Team TITA emerged as one of the most notable projects in the just concluded Women Build Celo Hackathon. I added TITA's repo to the celo.toml file.

Added the github repo of TITA

---

data/ecosystems/e/eos.toml

Hypha DAO is a project running on Telos and EOS Antelope chains. 
https://hypha.earth
Hypha has received a grant by the ENF to deploy our DAO product on EOS, we are currently working towards a beta launch. 
This PR contains all relevant, recent and public repositories for making Hypha DAO run, including
- The Hypha DAO Dapp
- Hypha Wallet (signing wallet)
- Various Hypha DAO smart contracts
- Utilities
Let me know if there are any questions, thank you!
I also see there's 2 more EOS ecosystem additions - I will be very happy to merge those changes into this PR in case there's conflicts. 
Thank you!

Adding Hypha DAO repos

---

data/ecosystems/a/avalanche.toml

Add [mnemonic-shamir-secret-sharing-cli](https://github.com/ava-labs/mnemonic-shamir-secret-sharing-cli) repo for Ava Labs.

Additions to Ava Labs

---

data/ecosystems/a/avalanche.toml

I've added links to the Avalanche NFT aggregator and the second-place Avalanche Akbank Refi hackathon project, Mono Carbon, to our repository for easy access and reference.

new Avalanche repos add

---

data/ecosystems/e/eos.toml

Hello!
I'd like to add some more recent data to the EOS ecosystem please. 
There are two primary orgs that are missing:
- [EOS Network Foundation](https://github.com/orgs/eosnetworkfoundation/) - EOS-specific code and EOS EVM
- [AntelopeIO](https://github.com/AntelopeIO) - The Antelope protocol (the successor to EOSIO, and the tech that the foundation develops to power EOS)
I've also added the most important repositories from both of them as well.

Adding EOS organizations and repositories

---

data/ecosystems/h/hedera.toml

- add `https://github.com/hedera-dev` to `github_organizations` in `data/ecosystems/h/hedera.toml`
- also add its repos under `[[repo]]` sections
- The `hedera-dev` github org contains many demo repos, code snippets, and templates used by developers building on Hedera

proj: add hedera-dev org + repos to the hedera config

---

data/ecosystems/p/polkadot-blockchain-academy.toml
data/ecosystems/p/polkadot.toml

Much of PBA's materials are now open source. Add PBA as a Polkadot sub-ecosystem and include the repos for documentation and exercises.

Add Polkadot Blockchain Academy

---

data/ecosystems/f/filecoin.toml
data/ecosystems/i/interplanetary-consensus.toml

Adds a number of missing repos, mainly related to Filecoin's [InterPlanetary Consensus](https://filecoin.io/blog/posts/achieving-breakthrough-scalability-with-interplanetary-consensus-ipc/).
It's not entirely clear whether it makes sense to duplicate repos in the parent and sub ecosystems, but that seems to be the case already for other entries.

Add InterPlanetary Consensus

---

data/ecosystems/c/celo.toml

add developer-tooling repo which contains packages split out from the core repo
remove celocli repo (not used)

Add developer tooling repo for celo

---

data/ecosystems/l/l2iterative.toml

L2 Iterative is a venture capital, but we have been hoping to become Paradigm or Geometry, in that we want to do more open-source work.
We already have released a few Rust-based crypto development tools for RISC Zero, specifically in the following two repos.
https://github.com/l2iterative/gdb0
https://github.com/l2iterative/profiler0
And we have been doing research related to verifying FHE in RISC Zero.
https://github.com/l2iterative/vfhe0
However, it is probably not the best idea to put this under RISC Zero's ecosystem. In the coming year, we plan to do the same for our other portfolio companies, including for Polyhedra, EigenLayer, Babylon, Elusiv. Therefore, we feel that it is a good idea to list as a separate organization, and we should be contributing a lot of new crypto-related …

Add L2 Iterative as an open-source organization

---

data/ecosystems/h/hedera.toml

* add https://github.com/the-creators-galaxy to github_organizations in data/ecosystems/h/hedera.toml
* also add its repos under [[repo]] sections
* The [the-creators-galaxy](https://github.com/the-creators-galaxy) github org contains open source projects used by creatives, builders and developers building on Hedera

Add the-creators-galaxy org and repos to hedera conifg.

---

data/ecosystems/s/safe-ecosystem.toml

Adding https://github.com/5afe as a new GitHub organization on the Safe Ecosystem.

Add 5afe as a Safe Ecosystem GitHub organization

---

data/ecosystems/s/solana.toml

We changed our GitHub org username from "StockpileProtocol" to "StockpileLabs", which created duplicates of the same repos in the list

Remove duplicate Stockpile repos

---

data/ecosystems/h/huff.toml

Added our open source project [Horseriders](https://github.com/BlocSoc-iitr/HorseRiders) to huff.toml
Horseriders is a complex math and Fast Fourier Transform Library for Huff and EVM Assembly

Added Horseriders to huff.toml

---

data/ecosystems/i/interest-protocol.toml

We had wrong repositories listed under our organization.

fix: remove wrong repositories

---

data/ecosystems/s/solana.toml

Solcial is a permissionless social network, that lets you invest in people.

add solcial to solana

---

data/ecosystems/p/polkadot-network.toml

The existing repo url does not exist. This PR adds the correct repo link.

fix ideal labs repo url

---

data/ecosystems/h/hedera.toml

DaVinciGraphNFTLocker is the new Service of DaVinciGraph for locking NFTs on the Hedera ecosystem.

add new DaVinciGraphNFTLocker repo

---

data/ecosystems/d/dojo-engine.toml
data/ecosystems/s/starknet.toml

corrected https://github.com/dojoengine/ org URL, also replaced all org/user URLs with repo URLs.

Add dojo engine

---

data/ecosystems/c/celo.toml
data/ecosystems/e/ethereum-hackathons.toml
data/ecosystems/g/gnosis-chain.toml
data/ecosystems/g/gnosis.toml
data/ecosystems/n/near.toml
data/ecosystems/p/polygon.toml

This PR adds:
- [Spark Nexus](https://github.com/Deepcryptodive/spark-nexus) to Near, Gnosis, Ethereum and Polygon
- [Spark Data Service](https://github.com/Deepcryptodive/spark-data-service) to Gnosis, Ethereum and Polygon
- [HaloFi](https://github.com/Good-Ghosting/goodghosting-protocol-v2) (aka GoodGhosting v2) to Celo and Polygon

Add Spark Nexus, Spark Data Service & HaloFi 

---

data/ecosystems/f/fennel.toml

Fennel is a Web3 communications hub for medical, humanitarian, and emergency services technologies.

Added Fennel Protocol

---

data/ecosystems/e/ethereum-consensus.toml

Eth-duties is a tool to track validator duties in order to help you decide when to have maintenance periods for your infrastructure or your deployments so that you do not miss any important/big rewards.

Add eth-duties to ethereum-consensus ecosystem

---

data/ecosystems/w/web3-protocol.toml

The GitHub Web3 Protocol organization is home to libraries and implementations of the
[IANA-standardized `web3://` URI scheme](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), defined in Ethereum's [ERC-6860](https://eips.ethereum.org/EIPS/eip-6860).
This protocol puts entire website logic onchain and essentially turns an EVM chain into an execution environment for web server code.
The listed repositories include implementations of ERC-6860 client libraries, as well as a web browser extension and a Chromium fork that implements the `web3://` URI scheme.

Add web3:// protocol sub-ecosystem to Ethereum.

---

data/ecosystems/a/aevo.toml
data/ecosystems/a/astria.toml
data/ecosystems/c/celenium.toml
data/ecosystems/c/celestia.toml
data/ecosystems/l/lyra.toml
data/ecosystems/m/manta-network.toml
data/ecosystems/o/orderly-network.toml
data/ecosystems/p/public-goods-network.toml

Added ecosystem level information for [Celenium.io](https://celenium.io) - Blockchain Explorer for Celestia and based on it networks
Celenium.io is now a blockchain explorer that provides not just information about the Celestia network, but also insights into the broader ecosystem built around Celestia. This means you can use Celenium.io to explore not only the Celestia blockchain itself, but also the activity and data of other networks that are built on top of Celestia.

Added Celenium Ecosystem

---

data/ecosystems/r/radix-dlt.toml

fomo_staking is the staking contract used by the $FOMO token on Radix DLT

add fomo_staking to radix-dlt

---

data/ecosystems/f/frequency.toml
data/ecosystems/p/project-liberty.toml

The Frequency Chain has moved to a separate GitHub organization.
- Updated the Frequency ecosystem to just have the github_organization
- Updated the Project Liberty ecosystem to just reference the Protocol: DSNP

Update for the new separate GitHub organization for Frequency

---

data/ecosystems/a/arbitrum.toml
data/ecosystems/o/optimism.toml
data/ecosystems/p/polygon.toml
data/ecosystems/s/starknet.toml

- Add [Create Nextjs Dapp](https://github.com/swiiny/create-nextjs-dapp) to Ethereum ecosystem
- Add [Cryptalk](https://github.com/swiiny/cryptalk) to Ethereum ecosystem
I've noticed that some repositories were duplicated after I've updated my GitHub handle few months ago.
- [https://github.com/JeremyTheintz/create-nextjs-dapp](https://github.com/JeremyTheintz/create-nextjs-dapp) -> [https://github.com/swiiny/create-nextjs-dapp](https://github.com/swiiny/create-nextjs-dapp)
- [https://github.com/JeremyTheintz/poc-land](https://github.com/JeremyTheintz/poc-land) -> [https://github.com/swiiny/poc-land](https://github.com/swiiny/poc-land)
- [https://github.com/JeremyTheintz/remix-project](https://github.com/JeremyTheintz/remix-project) -> …

chore: add swiiny/create-nextjs-dapp repo to ethereum ecosystem

---

data/ecosystems/s/stellar.toml

I took a bit of inspiration from another PR I saw, where a user was search for relevant SDKs declared in repo dependencies on GitHub, and adding them to an ecosystem's toml file. I've done similar, but tried to be a little more targeted than the PR I saw doing this.
The GH search I was using matched any repos with:
- `package.json` files including `stellar-sdk` or `stellar-base` as a dependency.
- `pyproject.toml` or `requirements.txt` files specifying `stellar-sdk` or `stellar_sdk` as a dependency.
- `Cargo.toml` files specifying `soroban-sdk` as a dependency.
- Weeds out any repo URLs that are already part of `stellar.toml` or any of the `stellar.toml` github orgs or sub-ecosystems.
I didn't want to search in any `yarn.lock`, etc. files, seemed like it would be way too broad of a net. …

add new stellar repos from github search results

---

data/ecosystems/c/cheesecake-labs.toml
data/ecosystems/s/stellar.toml

Cheesecake Labs is a very active dev organization in the Stellar ecosystem. This commit adds them as their own sub-ecosystem of Stellar. It seemed like a sub-ecosystem was warranted for two reasons:
1. (Mainly this one) They've developed their own `stellar-plus` SDK which wraps/enhances the SDF-maintained JavaScript SDK. There are several repositories using that as a dependency (as can be seen at the bottom of the [new] `cheesecake-labs.toml` file).
2. There's quite a long list of repos in their GH org.
If there's a better rubric you all use for determining if something is more fit to be in the `sub_ecosystems` vs the `github_organizations`, I'm more than happy to adjust this (and any following) PRs accordingly.
Thanks!
> _Note:_ I'm well aware that we're past the deadline for the midyear …

Add Cheesecake Labs as a sub-ecosystem of Stellar

---

data/ecosystems/s/stellar.toml

Previously, our `stellar.toml` file included the `fluxitystellar` GH org, which appears to have been renamed or folded into the `luanlabs` GH org. `fluxitystellar` was removed in 78025b3a85220a93b653ada9e029df010d8ecfaf. This PR adds the new org to the `stellar.toml` file.
> _Note:_ I'm well aware that we're past the deadline for the midyear update, and I have no expectations that this change would be included/reflected in that midyear data. Just trying to keep things up-to-date moving forward.

add Luan labs GH org, new name for fluxitystellar

---

data/ecosystems/c/cosmos-network.toml
data/ecosystems/s/structs.toml

This PR adds a Structs entry as it's own ecosystem, as well as adds it as a sub-ecosystem to the Cosmos Network. 
In the distant future, the species of the galaxy are embroiled in a race for Alpha Matter—the rare and dangerous substance that fuels galactic civilization. Players take command of Structs, a race of sentient machines, to conquer worlds, forge alliances, defeat enemies and expand their influence.
[Structs](https://playstructs.com) is a space-based strategy game designed around community play. Players and Guilds compete to mine Alpha Matter ($ALPHA), raid enemies, and defend their own resources in strategic PVP battles.
Alpha Matter fuels player growth and the infrastructure of the game itself, will be tradable for in-game assets or influence, and grants players a stake in the …

Add Structs to the Crypto Ecosystems repo

---

data/ecosystems/a/algorand.toml

Removed 1 repo spamming commits, which fakes developer activity.
- `algotables/algotables.github.io`
- Spams one or more commits a minute with a Google Script. Usually the commits are [empty](https://github.com/algotables/algotables.github.io/commit/ff1e9e9f118c47811ab007f09d0102f88a96af9b).
- Doesn't interact with the blockchain, or provide documentation either.
- Doesn't provide developer tools as the README suggests.
This skews rankings on websites using the `crypto-ecosystems` dataset.

Update algorand.toml: Remove repo spamming commits, which fakes developer activity

---

data/ecosystems/s/solana.toml

The correct repo is `michaelhly/solana-py`.
The fishy repo is `michealhly/solana-py`.

Remove fishy solana-py repository

---

data/ecosystems/d/dojo-engine.toml

Added the Haiku repo to the dojo ecosystem.
Haiku is a tool to easily add AI generated content to games developed using the dojo engine.
https://github.com/tensai-labs/haiku

add haiku to dojo ecosystem

---

data/ecosystems/h/hedera.toml

Adds Tolam Earth's GitHub organization account to the file. Also adds Tolam Earth as a sub-ecosystem of the Hedera ecosystem.

Adds Tolam Earth

---

src/main.rs

- Add DirectoryCreationError variant to CEError enum
- Replace unwrap() with safe directory creation error handling
- Propagate directory creation errors properly through Result

fix: improve directory creation error handling

---

data/ecosystems/d/duinocoin.toml

… and decentralized ways of storing funds. Duino-Coins can be converted to wDUCO, bscDUCO or others which are the same Duino-Coins but "wrapped" (stored) on other networks as tokens. An example tutorial on using wDUCO is available in the wDUCO wiki. Coins can be wrapped directly from your web Wallet - click the Wrap Coins button to start.
Simple, eco-friendly, centralized coin that can be mined with Arduinos, ESP boards, Raspberry Pis, computers, and many more (including Wi-Fi routers, smart TVs, smartphones, smartwatches, SBCs and other MCUs).

Submit the Duino-Coin support

---

data/ecosystems/z/zksync.toml

The following repositories are using either (or both) of the following tools:
- [zksyncchainchecker](https://github.com/Cyfrin/foundry-devops)
- [titanoboa-zksync](https://github.com/vyperlang/titanoboa-zksync)
Due to this, they should be included in the ZKsync ecosystem.

feat: zksync updates from updraft

---

data/ecosystems/d/dexkit.toml

To include [DexAppBuiler monorepo](https://github.com/DexKit/dexkit-monorepo), now open source.

Add DexKit monorepo repository

---

migrations/2025-05-28T140404_mutations

TriggerX is an automation protocol AVS under development on EigenLayer platform. You can know more about us [here](https://www.triggerx.network/).

add TriggerX sub ecosystem under EigenLayer

---

migrations/2025-06-27T152000_add_wamimi_aztec_projects

This PR adds four open-source projects built with Noir and Aztec to the Electric Capital ecosystem tracker. These include zk apps and learning resources focused on zero-knowledge proofs. Repos are tagged under both the Aztec and NoirLang ecosystems.
Thanks

Add Noir + Aztec repos by wamimi to ecosystem

---

migrations/2025-07-04T182057_algorand_updates

Added new repo for Algo Git Squad - [ARC69 NFT Minting DApp](https://github.com/VJLIVE/Algorand-ARC69-NFT-Minting-DApp)

Added new repo for algo git squad - ARC69 NFT Minting DApp

---

migrations/2025-07-08T235959_algorand_updates

Add two repositories to Algorand ecosystem and connecting GoPlausible as a child to Algorand ecosystem.
- [Algorand Remote MCP](https://github.com/GoPlausible/algorand-remote-mcp)
- [Ultrade MCP](https://github.com/ultrade-org/ultrade-mcp)

Add Repos to Algorand Ecosystem

---

migrations/2025-07-07T182400_add_noir_zkp_bounds_check

Adds a new Noir example project for noir zkp bounds check  to the "Noir Lang" ecosystem.
Repository: https://github.com/cypriansakwa/noir_zkp_bounds_check
Tags: #example #zkp #zk-circuit #noir

Add noir_zkp_bounds_check ecosystem with Noir ZKP bounds check

---

migrations/2025-07-09T234259_paydece_updates

This PR adds PayDece P2P escrow smart contracts to Polygon and Base ecosystems.
- **Project**: PayDece (https://paydece.io)
- **Type**: Peer-to-peer escrow system for secure transactions
- **Repository**: https://github.com/PayDece/paydece-contracts
- **Audit**: Audited by Hacken (https://hacken.io/audits/paydece/)
- ✅ Added PayDece to **Polygon** ecosystem with `#escrow` tag
- ✅ Added PayDece to **Base** ecosystem with `#escrow` tag
- ℹ️ PayDece already exists in Ethereum, BNB Chain, and Hardhat from previous migrations
- `migrations/2025-07-09T234259_paydece_updates`

Add PayDece P2P escrow to Polygon and Base networks

---

migrations/2025-07-16T234200_add-zkp_pedersen_range_safe

Adds the zkp_pedersen_range_safe project to the "Noir Lang" ecosystem. 
Repository: https://github.com/cypriansakwa/zkp_pedersen_range_safe
Tags: #zkp #zk-circuit #noir #aztec #example 

Add zkp_pedersen_range_safe project to the Noir Lang ecosystem

---

migrations/2025-07-22T063400_add-noir_private_matrix_proof

Adds a new Noir example project: noir_private_matrix_proof the "Noir Lang" ecosystem.
Repository: https://github.com/cypriansakwa/noir_private_matrix_proof 
Tags: #zkp #zk-circuit #noir #aztec

Add noir_private_matrix_proof project to the Noir Lang ecosystem

---

migrations/2025-07-22T085500_add-noir_linear_transform_proof

Adds a new Noir example project noir_linear_transform_proof  to the "Noir Lang" ecosystem. 
This circuit provides a zero-knowledge proof for verifying that a public output vector \( y \) is the result of a private linear transformation $y = W \cdot x$, where both the matrix $W$ and the input vector $x$ remain hidden.
Repository: https://github.com/cypriansakwa/noir_linear_transform_proof
Tags: #zkp #zk-circuit #noir #aztec

Add noir_linear_transform_proof project to the Noir Lang ecosystem

---

migrations/2025-08-26T110000_add_algorand_masterclasses_new_repos

Adds 18 newly forked repos for Algorand Web3 Masterclasses as a separate migration file,
per reviewer guidance. All tagged #developer-tool.
- POC Template Algorand Web3 Masterclasses: +17 forks
- Algorand Web3 Masterclasses POC: +1 fork

Add 18 new forks for Algorand Web3 Masterclasses (new migration)

---

migrations/2025-09-26T075550_add_stellar_repos

This migration adds **4 Stellar repositories** under the Stellar ecosystem in the Electric Capital crypto-ecosystems taxonomy.
**Context:**
We’re collaborating with [OnlyDust.com](https://onlydust.com), a platform where open-source web3 projects are built by independent builders.
We’ve been working closely with Stellar for the past 12 months.
Happy to answer any questions!

Add some Stellar repos

---

migrations/2025-10-02T231800_add-noir_sepolia_demo

Adds noir_sepolia_demo project to the "Noir Lang" ecosystem. 
Repository: https://github.com/cypriansakwa/noir_sepolia_demo 
Tags: #zkp #zk-circuit #noir #aztec 
Data Source: Electric Capital Crypto Ecosystems 

Add noir_sepolia_demo project to the Noir Lang ecosystem

---

migrations/2025-10-02T150500_add_namada_wallet
migrations/2025-10-02T173000_add_warden_faucet
migrations/2025-10-03T153000_add_namada_node_launcher

This PR adds the Namada Node Launcher repository under the Anoma ecosystem.
- Repository: https://github.com/anoma/namada-node-launcher
- Tags: infrastructure, rust
- Purpose: Provides tooling to easily launch and manage Namada nodes, simplifying validator and developer setup.

Add Namada Node Launcher repository to Anoma ecosystem

---

migrations/2025-10-02T150500_add_namada_wallet
migrations/2025-10-02T173000_add_warden_faucet
migrations/2025-10-05T101000_add_celo_developer_tooling

- Repository: https://github.com/celo-org/developer-tooling
- Tags: sdk, cli, typescript
- Purpose: Official JS/TS developer tooling and CLIs for the Celo ecosystem.

Add celo-org/developer-tooling to Celo ecosystem

---

migrations/2025-10-07T221800_add-zk-lessons-noir-psi-onchain

Adds zk-lessons-noir-psi-onchain project to the "Noir Lang" ecosystem. 
Repository: https://github.com/cypriansakwa/zk-lessons-noir-psi-onchain
Tags: #zkp #zk-circuit #noir #aztec #psi 
Data Source: Electric Capital Crypto Ecosystems 

Add zk-lessons-noir-psi-onchain project to the Noir Lang ecosystem
